#!/usr/bin/env zsh
#
# This can be used to check for and clear existing files out of the way of what these sets of dotfiles would take over.

starting_dir=$(pwd)
mypath=$0:A
mydir=$0:h:P
file_sources=(git tmux vim zsh)

find_all_source_dotfiles () {
  local dir=$1
  (cd $dir && find . -type f -print)
}

# Make way for our stow managed dotfiles
clean_old_dotfiles () {
  cd $mydir
  for dotdir in $file_sources; do
    if [[ -d $dotdir ]]; then
      for file in $(find_all_source_dotfiles $dotdir); do
        if [[ -a ~/${file} ]]; then
          print "Moving ~/${file} to ~/${file}.b4mkdot."
          mv ~/${file} ~/${file}.b4mkdot
        fi
      done
    fi
  done
  cd $starting_dir
}

clean_old_dotfiles
