#!/usr/bin/env zsh
#
#

while getopts 'M' OPT; do
  case $OPT in
    M) setup_MINIMAL=1 ;;
  esac
done

kernel=$(uname -s | tr "[:upper:]" "[:lower:]")
case "$(uname -m)" in
  x86_64)
    machine=amd64
    ;;
  *)
    die "Machine $(uname -m) not supported by the installer. Sorry\n"
    ;;
esac

# Check if we set up a file for public github settings. On my work machine, out local github settings are in my default environment and I use direnv to set the public ones where needed.  direnv doesn't help in a script :)
if [[ -s ~/.github_public ]]; then
  source ~/.github_public
fi
# Make ~/.local/bin our official user bin dir
home_bin=~/.local/bin
if [[ ! -d $home_bin ]]; then
  mkdir -p $home_bin
fi
if [[ -d ${HOME}/bin && ! -L ${HOME}/bin ]]; then
  cp -n ${HOME}/bin/* ${HOME}/.local/bin
  mv ${HOME}/bin ${HOME}/bin-old
  ln -s $home_bin ${HOME}/bin
fi

## Like an "UPSERT," clone or update the git project and return if a config/install is warranetd because of initial clone or chanegs were pulled.
upinst_from_git() {
  readonly git_url=${1:?"Supply the project git url as first parameter to install_from_git()"}
  readonly repo_name=${${git_url##*/}%.git}
  readonly passed_clone_target=${2}
  if [[ -z ${passed_clone_target// } ]]; then
    if [[ -d ${HOME}/git/github ]]; then
      local GITHUB_CLONE_DIR="${HOME}/git/github"
    else
      local GITHUB_CLONE_DIR="${HOME}/git"
    fi
    local clone_target="${GITHUB_CLONE_DIR}/${repo_name}"
  else
    local clone_target=${passed_clone_target}
  fi
  local EXIT_CODE=1 # this is an exit code, so "1" means false/fail
  if [[ -d ${clone_target} ]]; then
    cd $clone_target
    git remote update
    readonly local_ref=$(git rev-parse @)
    readonly remote_ref=$(git rev-parse @{u})
    if [[ $local_ref != $remote_ref ]]; then
      git pull
      EXIT_CODE=0
    fi
  else
    git clone $git_url $clone_target
    EXIT_CODE=0
  fi
  return $EXIT_CODE
}

INITIAL_PWD=$PWD
# OS Type specific stuff first
case $(uname) in
  Linux)
    source /etc/os-release
    if [[ $ID != "ubuntu" ]]; then
      echo "I only wrote this for ubuntu."
      exit 1
    fi
    SCRIPT_HOME=$(readlink -f ${0%/*})
    # Versions
    GOLANG_VERSION="1.17.5"
    NODEJS_VERSION="16.13.1"
    # Latest git
    if ! grep -q git-core /etc/apt/sources.list.d/*.list; then
      sudo add-apt-repository -y -u ppa:git-core/ppa
    fi
    for pkg in fonts-firacode curl git libcurl4-openssl-dev keychain jq tmux source-highlight fd-find stow autojump ripgrep; do
      dpkg -s $pkg &>/dev/null \
        || sudo apt-get install -y $pkg
    done
    if [[ ! -v setup_MINIMAL ]]; then
      for pkg in make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev; do
        dpkg -s $pkg &>/dev/null \
          || sudo apt-get install -y $pkg
      done
      # Latest github cli
      if ! grep -q cli.github /etc/apt/sources.list; then
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
        sudo apt-add-repository --update https://cli.github.com/packages
        sudo apt install gh
      fi
      # golang
      if [[ "go version go${GOLANG_VERSION} linux/amd64" != $(go version 2>/dev/null) ]]; then
        echo "Downloading and installing go ${GOLANG_VERSION}"
        curl -sLSO https://dl.google.com/go/go${GOLANG_VERSION}.${kernel}-${machine}.tar.gz \
          && sudo rm -rf /usr/local/go 2>/dev/null \
          && sudo tar -C /usr/local -xzf go${GOLANG_VERSION}.${kernel}-${machine}.tar.gz
        rm go${GOLANG_VERSION}.${kernel}-${machine}.tar.gz
        export PATH=${PATH}:/usr/local/go/bin
      fi
      # nodejs
      if [[ "v${NODEJS_VERSION}" != $(node --version 2>/dev/null) ]]; then
        echo "Downloading and installing nodejs $NODEJS_VERSION"
        if [[ -L /usr/local/nodejs ]]; then
          OLD_NODEJS=$(readlink /usr/local/nodejs)
        fi
        curl -sLS  -o /tmp/node-v${NODEJS_VERSION}-linux-x64.tar.xz https://nodejs.org/dist/v${NODEJS_VERSION}/node-v${NODEJS_VERSION}-linux-x64.tar.xz \
          && sudo tar -xJf /tmp/node-v${NODEJS_VERSION}-linux-x64.tar.xz -C /usr/local/
        if [[ -d /usr/local/node-v${NODEJS_VERSION}-linux-x64 ]]; then
          sudo rm /usr/local/nodejs
          sudo ln -s /usr/local/node-v${NODEJS_VERSION}-linux-x64 /usr/local/nodejs
        fi
        if [[ -v OLD_NODEJS && "$OLD_NODEJS" != $(readlink /usr/local/nodejs) ]]; then
          sudo rm -rf $OLD_NODEJS
        fi
        PATH=/usr/local/nodejs/bin:$PATH
      fi
      # Make sure we set an npm prefix for our user.
      npm config set prefix '~/.local/'
      # Install jsonlint
      npm install --global jsonlint
      # Install prettier
      npm install --global prettier
      # Build ugrep
      echo "ugrep"
      if upinst_from_git https://github.com/Genivia/ugrep ~/git/ugrep; then
        for pkg in libpcre2-dev zlib1g-dev libbz2-dev liblzma-dev liblz4-dev; do
          dpkg -s $pkg &>/dev/null \
            || sudo apt-get install -y $pkg
        done
        cd ~/git/ugrep
        ./build.sh --quiet
        cp bin/ugrep $home_bin
        [[ -L $home_bin/ug ]] || cp /bin/ug $home_bin
      fi
      # install fzf
      echo "fzf"
      if upinst_from_git https://github.com/junegunn/fzf ~/.fzf; then
        (cd ~/.fzf && ./install --bin)
      fi
      if [[ $VERSION_ID -ge 19.10 ]]; then
        gdelta_pkg="git-delta"
        lsd_pkg="lsd"
      else
        gdelta_pkg="git-delta-musl"
        lsd_pkg="lsd-musl"
      fi
      # git-delta
      echo "git-delta"
      curl -sLS $(curl -s https://api.github.com/repos/dandavison/delta/releases/latest | jq -r '.assets[].browser_download_url' | grep -E "${gdelta_pkg}_.*_amd64\.deb") -o /tmp/git-delta-latest_amd64.deb \
        && sudo dpkg --install --skip-same-version /tmp/git-delta-latest_amd64.deb
      # bat
      echo "bat"
      curl -sLS $(curl -s https://api.github.com/repos/sharkdp/bat/releases/latest | jq -r '.assets[].browser_download_url' | grep -E 'bat_.*_amd64.deb') -o /tmp/bat-latest.amd64.deb \
        && sudo dpkg --install --skip-same-version /tmp/bat-latest.amd64.deb
      echo "dive"
      curl -sLS $(curl -s https://api.github.com/repos/wagoodman/dive/releases/latest | jq -r '.assets[].browser_download_url' | grep '_amd64.deb') -o /tmp/dive-latest.amd64.deb \
        && sudo dpkg --install --skip-same-version /tmp/dive-latest.amd64.deb
      # lsd
      echo "lsd"
      curl -sLS $(curl -s https://api.github.com/repos/Peltoche/lsd/releases/latest | jq -r '.assets[].browser_download_url' | grep -E "${lsd_pkg}_.*_amd64\.deb") -o /tmp/lsd-latest.amd64.deb \
        && sudo dpkg --install --skip-same-version /tmp/lsd-latest.amd64.deb
      # chruby
      echo "chruby"
      eval $(grep '^CHRUBY_VERSION' /usr/local/share/chruby/chruby.sh)
      if [[ $CHRUBY_VERSION == "0.3.9" ]]; then
        echo "up to date"
      else
        curl -sLS https://github.com/postmodern/chruby/archive/v0.3.9.tar.gz -o chruby-0.3.9.tar.gz \
          && tar -xzf chruby-0.3.9.tar.gz \
          && cd chruby-0.3.9/ \
          && sudo make install
      fi
      # ruby-install
      echo "ruby-install"
      if [[ $(ruby-install --version | awk '{print $2}') == "0.8.3" ]]; then
        echo "up to date"
      else
        curl -sLS https://github.com/postmodern/ruby-install/archive/v0.8.3.tar.gz -o ruby-install-0.8.3.tar.gz \
          && tar -xzf ruby-install-0.8.3.tar.gz \
          && cd ruby-install-0.8.3/ \
          && sudo make install
      fi
      # direnv
      echo "direnv"
      direnv_download_url=$(curl -sLS https://api.github.com/repos/direnv/direnv/releases/latest | jq -r '.assets[].browser_download_url' | grep "direnv.$kernel.$machine")
      if whence direnv &>/dev/null; then
        direnv_latest_version=$(cut -d/ -f8 <<<$direnv_download_url)
        direnv_installed_version=$(direnv --version)
        if [[ "$direnv_latest_version" != "v${direnv_installed_version}" ]]; then
          curl -sL $direnv_download_url -o $home_bin/direnv && chmod 755 $home_bin/direnv
        fi
      else
        curl -sL $direnv_download_url -o $home_bin/direnv && chmod 755 $home_bin/direnv
      fi
      # awscli
      echo "awscli"
      curl -sLS "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
        && rm -rf aws && unzip -q awscliv2.zip \
        && if [[ -d /usr/local/aws-cli/v2 ]]; then
          /usr/local/bin/aws --version
          sudo ./aws/install --update
          # Prune old installs
          for version in /usr/local/aws-cli/v2/?*.?*.?*; do
            [[ $(readlink /usr/local/aws-cli/v2/current) == "$version" ]] || sudo rm -rf $version
          done
        else
          sudo ./aws/install
        fi
      /usr/local/bin/aws --version
      # shfmt
      GO111MODULE=on go install mvdan.cc/sh/v3/cmd/shfmt@latest
      # Build batextras
      echo "batextras"
      if upinst_from_git https://github.com/eth-p/bat-extras; then
        cd ~/git/bat-extars
        ./build.sh --no-verify \
        && cp bin/* $home_bin
      fi
      echo "kubectl"
      KUBECTL_STABLE=$(curl -sLS https://storage.googleapis.com/kubernetes-release/release/stable.txt)
      MY_KUBECTL_VERSION=$(kubectl version --client --short 2>/dev/null | awk '{print $3}')
      if [[ $KUBECTL_STABLE != $MY_KUBECTL_VERSION ]]; then
        curl -sLS https://storage.googleapis.com/kubernetes-release/release/$(curl -sLS https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl -o ${home_bin}/kubectl \
          && chmod 755 ${home_bin}/kubectl
      fi
    fi
    ;;
  Darwin)
    if command -v brew &>/dev/null; then
      echo "homebrew already installed"
    else
      echo "Installing homebrew"
      /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi
    brew tap homebrew/cask-fonts
    brew list font-fira-code --cask &>/dev/null || brew install font-fira-code --cask
    # Base stuff we need.
    NEEDED_PACKAGES=(
      openssl
      readline
      sqlite
      xz
      zlib
      keychain
      kubernetes-cli
      coreutils
      findutils
      go
      shfmt
      bat
      ugrep
      bat-extras
      git
      chruby
      ruby-install
      direnv
      jq
      jsonlint
      prettier
      gh
      lsd
      stow
      gnu-getopt
      autojump
      fd
      ripgrep
      fzf
    )
    brew list > /tmp/brews.$$
    for pkg in ${NEEDED_PACKAGES[*]}; do
      grep -w $pkg /tmp/brews.$$ &>/dev/null \
        || brew install $pkg
    done
    SCRIPT_HOME=$(greadlink -f ${0%/*})
    # dive
    curl -sLS $(curl -s https://api.github.com/repos/wagoodman/dive/releases/latest | jq -r '.assets[].browser_download_url' | grep -i ${kernel}_${machine}) -o /tmp/dive-latest.tgz \
      && mkdir -p /tmp/dive.$$ \
      && tar -C /tmp/dive.$$ -xzf /tmp/dive-latest.tgz \
      && rm /tmp/dive-latest.tgz \
      && cp /tmp/dive.$$/dive ${home_bin} \
      && chmod 755 ${home_bin}/dive
    ;;
  *)
    echo "Unknown OS type"
    exit
    ;;
esac

# starship (prompt)
print -n "starship: "
if whence starship &> /dev/null; then
  installed_starship_version=$(starship --version |grep tag |cut -d: -f2)
  # This isn't working on work machine with direnv for ~/git/github, somehow it is not picking up the GH_TOKEN or something
  latest_starship_version=$(gh release list --limit 1 --repo starship/starship |awk '{print $1}')
  if [[ $installed_starship_version != $latest_starship_version ]]; then
    print "updating."
    if [[ $(uname) == "Linux" ]]; then
      curl -fsSL https://starship.rs/install.sh | bash -s - -y -b ${home_bin} -p unknown-linux-gnu
    else
      curl -fsSL https://starship.rs/install.sh | bash -s - -y -b ${home_bin}
    fi
    starship --version
  else
    print "up to date."
  fi
else
  print "installing."
  if [[ $(uname) == "Linux" ]]; then
    curl -fsSL https://starship.rs/install.sh | bash -s - -y -b ${home_bin} -p unknown-linux-gnu
  else
    curl -fsSL https://starship.rs/install.sh | bash -s - -y -b ${home_bin}
  fi
  starship --version
fi

if [[ ! -v setup_MINIMAL ]]; then
  # tfswitch
  echo "tfswitch"
  curl -sLS https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | bash -s - -b ${home_bin}

  # k9s
  echo "k9s"
  curl -sLS $(curl -sLS https://api.github.com/repos/derailed/k9s/releases/latest | jq -r '.assets[].browser_download_url' | grep -i ${kernel}_$(uname -m)) -o /tmp/k9s-latest.tgz \
    && mkdir -p /tmp/k9s.$$ \
    && tar -C /tmp/k9s.$$ -xzf /tmp/k9s-latest.tgz \
    && rm /tmp/k9s-latest.tgz \
    && cp /tmp/k9s.$$/k9s ${home_bin} \
    && chmod 755 ${home_bin}/k9s

  # cheat
  echo "cheat"
  curl -sLS https://github.com/cheat/cheat/releases/latest/download/cheat-${kernel}-${machine}.gz -o /tmp/cheat.tgz \
    && gunzip -c /tmp/cheat.tgz >${home_bin}/cheat
  chmod 755 ${home_bin}/cheat
  ##
  echo "pyenv"
  if upinst_from_git https://github.com/pyenv/pyenv.git ~/.pyenv; then
    (cd ~/.pyenv && src/configure && make -C src)
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init --path)"
  fi
  if [[ -d ~/.pyenv/plugins/pyenv-virtualenv ]]; then
    git pull
  else
    git clone https://github.com/pyenv/pyenv-virtualenv.git ~/.pyenv/plugins/pyenv-virtualenv
  fi
  if ! pyenv global 3.10.0 &>/dev/null; then
    print "Using pyenv to install python 3.10.0"
    pyenv install 3.10.0
    pyenv global 3.10.0
  fi
  echo "Python packages:"
  echo "pre-commit"
  if command -v pre-commit >/dev/null 2>&1; then
    python -m pip install --upgrade --user pre-commit | grep -v "Requirement already satisfied"
  else
    python -m pip install --user pre-commit
  fi
  echo "boto3"
  if command python -m pip show boto3 >/dev/null 2>&1; then
    python -m pip install --upgrade --user 'boto3[crt]' | grep -v "Requirement already satisfied"
  else
    python -m pip install --user 'boto3[crt]'
  fi
  echo "flake8"
  if command python -m pip show flake8 >/dev/null 2>&1; then
    python -m pip install --upgrade --user 'flake8' | grep -v "Requirement already satisfied"
  else
    python -m pip install --user 'flake8'
  fi
  echo "flake8-bugbear"
  if command python -m pip show flake8-bugbear >/dev/null 2>&1; then
    python -m pip install --upgrade --user 'flake8-bugbear' | grep -v "Requirement already satisfied"
  else
    python -m pip install --user 'flake8-bugbear'
  fi
  echo "pylint"
  if command python -m pip show pylint >/dev/null 2>&1; then
    python -m pip install --upgrade --user 'pylint' | grep -v "Requirement already satisfied"
  else
    python -m pip install --user 'pylint'
  fi
  echo "black"
  if command python -m pip show black >/dev/null 2>&1; then
    python -m pip install --upgrade --user 'black' | grep -v "Requirement already satisfied"
  else
    python -m pip install --user 'black'
  fi
fi

# antibody
echo "antibody"
curl -sfLS git.io/antibody | bash -s - -b ${home_bin}
