#!/usr/bin/env zsh

# Requirements
command -v stow &>/dev/null || {
  print -u 2 "GNU stow is required to link dotfiles into place. https://www.gnu.org/software/stow/"
  exit 1
}

if command getopt -T &>/dev/null; then
  local rv=$?
  if [ $rv != 4 ]; then
    print -u 2 "You need GNU getopt installed and in your path before the non GNU one that is there now."
    exit 1
  else
    print -u 2 "GNU getopt is required for this."
    exit 1
  fi
fi

usage () {
  print "Usage $0:t [ --package <pkg> ] [ -v | --verbose ] [ --dry-run | --simulate ] [ --restow ]"
  exit 2
}

if PARSED_ARGUMENTS=$(getopt -n $0:t -o p:,R,v --longoptions dry-run,package:,restow,simulate,verbose -- "$@"); then
  :
else
  usage
fi

eval set -- "$PARSED_ARGUMENTS"
STOW_TYPE="stow"
STOW_PKGS=(git tmux vim zsh tools_and_wrappers)
while :
do
  case "$1" in
    -v | --verbose)  VERBOSE=1 ; shift ;;
    --dry-run | --simulate) SIMULATE=1  ; shift ;;
    -R | --restow) STOW_TYPE="restow" ; shift;;
    -p | --package) STOW_PKGS="$2" ; shift 2 ;;
    --) shift; break ;;
    *) print "Unexpected option: $1 - this should not happen."
       usage ;;
  esac
done

mydir=$0:h:P

stow_command="stow --dir $mydir --target $HOME"
if [ ${+VERBOSE} = 1 ]; then
  stow_command+=" --verbose"
fi
if [ ${+SIMULATE} = 1 ]; then
  stow_command+=" --simulate"
fi
for pkg in $STOW_PKGS; do
  stow_command+=" --${STOW_TYPE} $pkg"
done

[  ${+VERBOSE} = 1 ] && print $stow_command
eval $stow_command
