#!/usr/bin/env zsh

if [[ -d ~/.local/share/nvim/site/pack/packer/start/packer.nvim ]]; then
  :
else
  git clone --depth 1 https://github.com/wbthomason/packer.nvim\
    ~/.local/share/nvim/site/pack/packer/start/packer.nvim
fi
# This basically installs shims for ruby and python for neovim
python3 -m pip install --user --upgrade pynvim
gem install neovim
