# Open any image in the full kitty window by clicking on it
protocol file
mime image/*
action launch --type=overlay kitty +kitten icat --hold ${FILE_PATH}

# Open any text file using nvim in the full kitty window by clicking on it
protocol file
mime text/*
action launch --type=os-window ${EDITOR} ${FILE_PATH}

protocol file
ext lua,rb,py,go
action launch --type=os-window ${EDITOR} ${FILE_PATH}
