# Open any image in the full kitty window by clicking on it
protocol file
mime image/*
action launch --type=overlay kitty +kitten icat --hold ${FILE_PATH}

# xdg-open doesn't seem to work here. Hard coded firefox
protocol file
ext html
action launch --type=os-window firefox ${FILE_PATH}

# Open any text file using nvim in the full kitty window by clicking on it
protocol file
mime text/*
action launch --type=os-window ${EDITOR} ${FILE_PATH}

protocol file
ext lua,rb,py,go
action launch --type=os-window ${EDITOR} ${FILE_PATH}

# Open ssh URLs with ssh command
protocol ssh
action launch --type=os-window ssh $URL
