format = """\
    $username\
    $hostname\
    $kubernetes\
    $directory\
    $git_branch\
    $git_state\
    $git_status\
    $package\
    $dotnet\
    $golang\
    $java\
    $python\
    $ruby\
    $rust\
    $nix_shell\
    $conda\
    $memory_usage\
    $aws\
    $terraform\
    $env_var\
    $cmd_duration\
    $line_break\
    $jobs\
    $battery\
    $time\
    $character\
"""

command_timeout = 750

[conda]
disabled = true

[directory]
truncation_length=10
truncate_to_repo=false

[dotnet]
disabled = true

[git_status]
disabled=false

[nodejs]
disabled = true

[terraform]
format = "[$symbol$version]($style) "
disabled=false

[time]
disabled = false
format = "[$time]($style) "

[hostname]
disabled=false
ssh_only=false
