format = """$all"""
# Put language info and aws into rprompt
right_format = """$java $python $ruby $go $perl"""

# A continuation prompt that displays two filled in arrows
continuation_prompt = "▶▶(inverted) "

[aws]
format = '[$symbol($profile )(\($region\) )]($style)'
symbol = " "
style = "#ff9900" # aws orange
force_display=true
[aws.region_aliases]
ap-southeast-2 = "australia"
sa-east-1 = "brazil"
us-east-2 = "ohio"
us-west-2 = "oregon"

[conda]
disabled = true

[directory]
truncation_length = 10
truncate_to_repo = false

[dotnet]
disabled = true

[git_branch]
disabled = false
format = "on [$symbol$remote_name/$branch]($style) "
always_show_remote = true

[git_metrics]
disabled = false

[git_commit]
disabled = false
tag_disabled = false

[hostname]
disabled = false
ssh_only = false

[kubernetes]
disabled = false
[kubernetes.context_aliases]
"aws-br-wharf-production" = "br-prod"
"aws-br-wharf-staging" = "br-staging"
"aws-oh-wharf-production" = "oh-prod"
"aws-oh-wharf-staging" = "oh-staging"
"onprem-elk-wharf-monkeybusiness" = "monkeybusiness"
"onprem-elk-wharf-staging" = "elk-staging"
"onprem-oak-wharf-production" = "oak-prod"

[nodejs]
disabled = true

[perl]
format = '[$symbol($version )]($style)'

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[ruby]
detect_variables = []
format = '[$symbol($version )]($style)'

[rust]
format = '[$symbol($version )]($style)'

[status]
disabled = false

[terraform]
format = "[$symbol$version]($style) "
detect_files = ["atlantis.yaml"]
disabled = false

[time]
disabled = false
format = "[$time]($style) "
