format = """$all"""
# Put language info and aws into rprompt
right_format = """$java $python $ruby $go $perl"""

# A continuation prompt that displays two filled in arrows
continuation_prompt = "▶▶(inverted) "

[aws]
format = '[$symbol($profile )(\($region\) )]($style)'
symbol = "󰸏 "
style = "#ff9900" # aws orange

[aws.region_aliases]
ap-southeast-2 = "australia"
sa-east-1 = "brazil"
us-east-1 = "virginia"
us-east-2 = "ohio"
us-west-1 = "california"
us-west-2 = "oregon"

[conda]
disabled = true

[directory]
truncation_length = 10
truncate_to_repo = false

[dotnet]
disabled = true

[git_branch]
disabled = false
format = "on [$symbol$remote_name/$branch]($style) "
always_show_remote = true

[git_metrics]
disabled = false

[git_commit]
disabled = false
tag_disabled = false

[hostname]
disabled = false
ssh_only = false

[kubernetes]
disabled = false
contexts = [
  {context_pattern = "aws-br-wharf-production", context_alias = "br-prod"},
  {context_pattern = "aws-br-wharf-staging",context_alias = "br-staging"},
  {context_pattern = "aws-oh-wharf-production", context_alias = "oh-prod"},
  {context_pattern = "aws-oh-wharf-staging",context_alias = "oh-staging"},
  {context_pattern = "onprem-elk-wharf-monkeybusiness",context_alias = "monkeybusiness"},
  {context_pattern = "onprem-elk-wharf-staging",context_alias = "elk-staging"},
  {context_pattern = "onprem-oak-wharf-production",context_alias = "oak-prod"}
]

[nodejs]
disabled = true

[perl]
format = '[$symbol($version )]($style)'

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[ruby]
detect_variables = []
format = '[$symbol($version )]($style)'

[rust]
format = '[$symbol($version )]($style)'

[status]
disabled = false

[terraform]
format = "[$symbol$version]($style) "
detect_files = ["atlantis.yaml"]
disabled = false

[time]
disabled = false
format = "[$time]($style) "
