format = """\
    $username\
    $hostname\
    $kubernetes\
    $directory\
    $git_branch\
    $git_state\
    $git_status\
    $git_commit\
    $git_metrics\
    $package\
    $dotnet\
    $golang\
    $java\
    $python\
    $ruby\
    $rust\
    $nix_shell\
    $conda\
    $memory_usage\
    $aws\
    $terraform\
    $env_var\
    $cmd_duration\
    $line_break\
    $jobs\
    $battery\
    $time\
    $status\
    $character\
"""

# A continuation prompt that displays two filled in arrows
continuation_prompt = "▶▶(inverted) "

command_timeout = 750

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
symbol = " "
style = "#ff9900" # aws orange
force_display=true
# [aws.region_aliases]
# ap-southeast-2 = "au"
# sa-east-1 = "br"
# us-east-1 = "va"
# us-east-2 = "oh"
# us-west-2 = "or"

[conda]
disabled = true

[directory]
truncation_length = 10
truncate_to_repo = false

[dotnet]
disabled = true

[git_branch]
disabled = false
format = "on [$symbol$remote_name/$branch]($style) "
always_show_remote = true

[git_metrics]
disabled = false

[git_commit]
disabled = false
tag_disabled = false

[hostname]
disabled = false
ssh_only = false

[kubernetes]
disabled = false
[kubernetes.context_aliases]
"aws-br-wharf-production" = "br-prod"
"aws-br-wharf-staging" = "br-staging"
"aws-oh-wharf-production" = "oh-prod"
"aws-oh-wharf-staging" = "oh-staging"
"onprem-elk-wharf-monkeybusiness" = "monkeybusiness"
"onprem-elk-wharf-staging" = "elk-staging"
"onprem-oak-wharf-production" = "oak-prod"

[nodejs]
disabled = true

[ruby]
detect_variables = []

[status]
disabled = false

[terraform]
format = "[$symbol$version]($style) "
detect_files = ["atlantis.yaml"]
disabled = false

[time]
disabled = false
format = "[$time]($style) "
