return {
  {
    "nvim-treesitter/nvim-treesitter",
    -- tag = "v0.9.2",
    branch = "master",
    build = ":TSUpdate",
    dependencies = { "OXY2DEV/markview.nvim" },
    event = { "BufReadPost", "BufNewFile" },
    cmd = { "TSUpdateSync" },
    keys = {
      { "<c-space>", desc = "Increment selection" },
      { "<bs>", desc = "Schrink selection", mode = "x" },
    },
    lazy = false,
    ---@type TSConfig
    opts = {
      highlight = {
        enable = true,
        additional_vim_regex_highlighting = false,
      },
      indent = {
        enable = true,
      },
      context_commentstring = { enable = true, enable_autocmd = false },
      ensure_installed = {
        "awk",
        "bash",
        "c",
        "comment",
        "dockerfile",
        "go",
        "gomod",
        "hcl",
        "html",
        "java",
        "javascript",
        "json",
        "json5",
        "jq",
        "lua",
        "make",
        "markdown",
        "markdown_inline",
        "perl",
        "php",
        "python",
        "query",
        "regex",
        "ruby",
        "rust",
        "ssh_config",
        "terraform",
        "toml",
        "vim",
        "vimdoc",
        "yaml",
      },
      ignore_install = {
        "agda",
        "beancount",
        "c_sharp",
        "clojure",
        "cooklang",
        "cuda",
        "d",
        "dart",
        "dot",
        "elvish",
        "erlang", -- broken, 2022-12-11
        "gleam",
        "glimmer",
        "hack",
        "haskell",
        "heex",
        "kotlin",
        "ocaml",
        "ocaml_interface",
        "pascal",
        "pioasm",
        "pug",
        "scala",
        "supercollider",
        "vala",
      },
      incremental_selection = {
        enable = true,
        keymaps = {
          init_selection = "<C-space>",
          node_incremental = "<C-space>",
          scope_incremental = "<nop>",
          node_decremental = "<bs>",
        },
      },
    },
    ---@param opts TSConfig
    config = function(_, opts)
      require("nvim-treesitter.configs").setup(opts)
    end,
  },
}
