# Setting the prefix from C-b to C-a
set -g prefix C-a
# Free the original Ctrl-b prefix keybinding
unbind C-b

# set the status line's colors
# START:statuscolor
set -g status-style fg=white,bg=black
# END:statuscolor

# START:windowstatuscolor
setw -g window-status-style fg=cyan,dim,bg=default
# END:windowstatuscolor

# START:activewindowstatuscolor
setw -g window-status-current-style fg=white,bright,bg=red
# END:activewindowstatuscolor

# START:panecolors
set -g pane-border-style fg=green,bg=black
set -g pane-active-border-style fg=white,bg=yellow
setw -g window-style fg=colour240,bg=colour235
setw -g window-active-style fg=white,bg=black
# END:panecolors

# START:cmdlinecolors
set -g message-style fg=white,bright,bg=black
# END:cmdlinecolors

# START:statusleft
set -g status-left-length 40 
set -g status-left "#[fg=green]Session: #S@#h #[fg=yellow]#I #[fg=cyan]#P"
# END:statusleft

# Status line right side
# 15% | 28 Nov 18:15
# START: statusright
#set -g status-right "#{prefix_highlight} #[fg=cyan]%d %b %R"
# tmux-mem-cpu-load
set -g status-right "#{prefix_highlight} %d %b %R #[fg=green,bg=black]#(${TMUX_PLUGIN_MANAGER_PATH}tmux-mem-cpu-load/tmux-mem-cpu-load --powerline-right --mem-mode 2 --interval 5)#[default]"
set -g status-right-length 75
# END:statusright

# Update the status bar every five seconds
# START:updateinterval
set -g status-interval 5
# END:updateinterval

# Center the window list
# START:centerwindowlist
set -g status-justify centre
# END:centerwindowlist

# enable vi keys.
# START:vikeys
# setw -g mode-keys vi
# END:vikeys

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'thewtex/tmux-mem-cpu-load'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com/user/plugin'
# set -g @plugin 'git@bitbucket.com/user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
