[tools]
awscli = "2"
bat = "latest"
bat-extras = "latest"
cheat = "latest"
delta = "latest"
direnv = "latest"
dive = "latest"
fd = "latest"
go = "latest"
helm = "latest"
k9s = "latest"
kubectl = "latest"
lazygit = "latest"
lsd = "latest"
node = "lts"
tflint = "latest"
tfswitch = "latest"
zoxide = "latest"
usage = "latest"
cosign = "latest"

[settings]
not_found_auto_install = true
python_compile = true
go_set_gobin = false
go_set_gopath = false
