[tools]
neovim = "nightly"
node = "lts"
awscli = "latest"
go = "latest"
tflint = "latest"
k9s = "latest"
kubectl = "latest"
zoxide = "latest"
cheat = "latest"
delta = "latest"
helm = "latest"
tfswitch = "latest"
direnv = "latest"
dive = "latest"
github-cli = "latest"
python = "3.12"

[settings]
not_found_auto_install = true
python_compile = true
