[tools]
# keep-sorted start
"aqua:helm" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:neovim/neovim" = "latest"
"aqua:tofuutils/tenv" = "latest"
"aqua:yazi" = "latest"
"cargo:lsd" = "latest"
"cargo:tree-sitter-cli" = "latest"
"cargo:zoxide" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:github.com/google/keep-sorted" = "latest"
"go:github.com/wagoodman/dive" = "latest"
"pipx:ansible-core" = "latest"
"pipx:glances" = "latest"
"pipx:httpie" = "latest"
"pipx:identify" = "latest"
"pipx:jsonschema" = "latest"
"pipx:mdformat" = { version = "latest", pipx_args = "--preinstall mdformat-mkdocs --preinstall mdformat-admon" }
"pipx:pre-commit" = "latest"
"ubi:achannarasappa/ticker" = "latest"
"ubi:cargo-bins/cargo-binstall" = { version = "latest", tag_regex = '^\d+\.' }
"ubi:cheat/cheat" = "latest"
"ubi:direnv/direnv" = "latest"
"ubi:mikefarah/yq" = "latest"
"ubi:minamijoyo/hcledit" = "latest"
"ubi:mr-karan/doggo" = "latest"
"ubi:sharkdp/fd" = "latest"
"ubi:sigstore/cosign" = "latest"
"ubi:terraform-linters/tflint" = "latest"
"ubi:tmccombs/hcl2json" = "latest"
awscli = "2"
bat = "latest"
bat-extras = "latest"
cheat = "latest"
delta = "latest"
go = "latest"
goreleaser = "latest"
k9s = "latest"
kubectl = "latest"
lazygit = "latest"
node = "lts"
rust = "latest"
tflint = "latest"
usage = "latest"
zig = "latest"
# keep-sorted end

[settings]
# keep-sorted start
experimental = true
go_set_gobin = false
go_set_gopath = false
idiomatic_version_file_enable_tools = []
not_found_auto_install = true
python_compile = true
# keep-sorted end

[settings.cargo]
binstall = true
